// This file will be generated by Supabase CLI
// For now, we'll use a basic type definition
export interface Database {
  public: {
    Tables: {
      weights: {
        Row: {
          id: string;
          user_id: string;
          date: string;
          value: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          date: string;
          value: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          date?: string;
          value?: number;
          created_at?: string;
        };
      };
      user_profiles: {
        Row: {
          id: string;
          goal_weight: number | null;
          total_change_start_date: string | null;
          created_at: string;
        };
        Insert: {
          id: string;
          goal_weight?: number | null;
          total_change_start_date?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          goal_weight?: number | null;
          total_change_start_date?: string | null;
          created_at?: string;
        };
      };
    };
  };
}
